float:
  any:
  - base_args: ['@metric',Float]
    constructor: QPG
    disabled: false
    docker_tag: ann-benchmarks-qpg
    module: ann_benchmarks.algorithms.qpg
    name: qpg
    run_groups:
      a1:
        args: [{data_path: './test.fvecs', K: 128, smp: 36, iter: 15, alpha: 1.1, 
                M0: 64, M: 32, occ: 3, recallN: 10, rvsN: 8,  out_path: './graph.hnsw',  
                reranker: 'sq16', quantizer: 'sq8',
                qdim: 0, rdim: 0
              }]
        query_args: [[
                [10,1.0],
                [11,1.0],
                [12,1.0],
                [13,1.0],
                [15,1.0],
                [18,1.0],
                [22,1.0],
                [26,1.0],
                [28,1.0],
                [30,1.0],
                [35,1.0],
                [40,1.0],
                [45,1.0],
                [50,1.0],
                [55,1.0],
                [60,1.0],
                [65,1.0],
                [70,1.0],
                [80,1.0],
                [90,1.0],
                [100,1.0],
                [110,1.0],
                [120,1.0],
                [130,1.0],
                [140,1.0],
                [150,1.0],
                [160,1.0],
                [170,1.0],
                [180,1.0],
                [190,1.0],
                [200,1.0],
                [300,1.0],
                [400,1.0],
                [500,1.0],
                [600,1.0]
              
            ]]
      a2:
        args: [{data_path: './test.fvecs', K: 128, smp: 36, iter: 15, alpha: 1.1, 
                M0: 64, M: 32, occ: 3, recallN: 10, rvsN: 8,  out_path: './graph.hnsw',  
                reranker: 'sq16', quantizer: 'sq8',
                qdim: 128, rdim: 0
              }]
        query_args: [[
                [10,1.0],
                [11,1.0],
                [12,1.0],
                [13,1.0],
                [15,1.0],
                [18,1.0],
                [22,1.0],
                [26,1.0],
                [28,1.0],
                [30,1.0],
                [35,1.0],
                [40,1.0],
                [45,1.0],
                [50,1.0],
                [55,1.0],
                [60,1.0],
                [65,1.0],
                [70,1.0],
                [75,1.0],
                [80,1.0],
                [85,1.0],
                [90,1.0],
                [95,1.0],
                [100,1.0],
                [105,1.0],
                [110,1.0],
                [115,1.0],
                [120,1.0],
                [125,1.0],
                [130,1.0],
                [135,1.0],
                [140,1.0]
            ]]
      a3:
        args: [{data_path: './test.fvecs', K: 128, smp: 36, iter: 15, alpha: 1.1, 
                M0: 32, M: 16, occ: 3, recallN: 10, rvsN: 8,  out_path: './graph.hnsw',  
                reranker: 'sq16', quantizer: 'sq8',
                qdim: 128, rdim: 0
              }]
        query_args: [[
                [10,1.0],
                [11,1.0],
                [12,1.0],
                [13,1.0],
                [15,1.0],
                [18,1.0],
                [22,1.0],
                [26,1.0],
                [28,1.0],
                [30,1.0],
                [35,1.0],
                [40,1.0],
                [45,1.0],
                [50,1.0],
                [55,1.0],
                [60,1.0],
                [65,1.0],
                [70,1.0],
                [75,1.0],
                [80,1.0],
                [85,1.0],
                [90,1.0],
                [95,1.0],
                [100,1.0],
                [105,1.0],
                [110,1.0],
                [115,1.0],
                [120,1.0],
                [125,1.0],
                [130,1.0],
                [135,1.0],
                [140,1.0]
            ]]
      a4:
        args: [{data_path: './test.fvecs', K: 128, smp: 36, iter: 15, alpha: 1.1, 
                M0: 32, M: 16, occ: 3, recallN: 10, rvsN: 8,  out_path: './graph.hnsw',  
                reranker: 'sq16', quantizer: 'sq8',
                qdim: 64, rdim: 0
              }]
        query_args: [[
                [10,1.0],
                [11,1.0],
                [12,1.0],
                [13,1.0],
                [15,1.0],
                [18,1.0],
                [22,1.0],
                [26,1.0],
                [28,1.0],
                [30,1.0],
                [35,1.0],
                [40,1.0],
                [45,1.0],
                [50,1.0],
                [55,1.0],
                [60,1.0],
                [65,1.0],
                [70,1.0],
                [75,1.0],
                [80,1.0],
                [85,1.0],
                [90,1.0],
                [95,1.0],
                [100,1.0],
                [105,1.0],
                [110,1.0],
                [115,1.0],
                [120,1.0],
                [125,1.0],
                [130,1.0],
                [135,1.0],
                [140,1.0]
            ]]
      a5:
        args: [{data_path: './test.fvecs', K: 128, smp: 36, iter: 15, alpha: 1.1, 
                M0: 32, M: 16, occ: 3, recallN: 10, rvsN: 8,  out_path: './graph.hnsw',  
                reranker: 'tc8', quantizer: 'sq8',
                qdim: 0, rdim: 0
              }]
        query_args: [[
                [10,1.0],
                [11,1.0],
                [12,1.0],
                [13,1.0],
                [15,1.0],
                [18,1.0],
                [22,1.0],
                [26,1.0],
                [28,1.0],
                [30,1.0],
                [35,1.0],
                [40,1.0],
                [45,1.0],
                [50,1.0],
                [55,1.0],
                [60,1.0],
                [65,1.0],
                [70,1.0],
                [75,1.0],
                [80,1.0],
                [85,1.0],
                [90,1.0],
                [95,1.0],
                [100,1.0],
                [105,1.0],
                [110,1.0],
                [115,1.0],
                [120,1.0],
                [125,1.0],
                [130,1.0],
                [135,1.0],
                [140,1.0],
                [160,1.0],
                [180,1.0],
                [200,1.0],
                [220,1.0],
                [240,1.0],
                [260,1.0],
                [280,1.0],
                [300,1.0],
                [320,1.0],
            ]]